# colors
WHITE = (255, 255, 255)
RED = (255, 0, 0)

# window configuration
WINDOW_WIDTH = 1000
WINDOW_HEIGHT = 600
WINDOW_SIZE = (WINDOW_WIDTH, WINDOW_HEIGHT)
FPS = 60

# player configuration
PLAYER_WIDTH = 30
PLAYER_HEIGHT = 30
PLAYER_SIZE = (PLAYER_WIDTH, PLAYER_HEIGHT)
PLAYER_ACC = 1
PLAYER_FRICTION = 0.1
